/*
 * Automatically generated C config: don't edit
 * Linux kernel version: KERNELVERSION
 * Tue Jul  8 12:02:08 2014
 */
#define AUTOCONF_INCLUDED
#define CONFIG_ALPHA_SOFT 1
#define CONFIG_CONTROL_DRAG_MENU 1
#define CONFIG_TOUCH_NONE 1
#define CONFIG_CONTROL_LJ_LOCK 1
#define CONFIG_CONTROL_GESTURE 1
#define CONFIG_CONTROL_CARTOON 1
#define CONFIG_CONTROL_LJ_DRAG_VERTICAL_EXPLAIN 1
#define CONFIG_CONTROL_STATIC_TEXT 1
#define CONFIG_USING_FONT 1
#define CONFIG_CONTROL_STATIC_IMAGE 1
#define CONFIG_CONTROL_LJ_SCREENSAVER 1
#define CONFIG_CONTROL_RADIO_BUTTONS 1
#define CONFIG_CONTROL_LJ_DRAG_IMAGE 1
#define CONFIG_DEBUG 1
#define CONFIG_CONTROL_BUTTON 1
